// graph/stateSchema.js
export const defaultState = {
  companyName:      "",
  companyProfile:   null,
  ticker:           "",
  financialData:    null,   // keep as-is, node is now node_financialData
  financialScore:   0,
  recentNews:       [],
  newsScore:        0,
  sentimentResult:  null,
  sentimentScore:   0,
  riskFactors:      [],
  riskScore:        0,
  moatAnalysis:     "",
  verdict:          "",
  confidenceScore:  0,
  reasoning:        "",
  summary:          "",
  steps:            [],
  errors:           [],
  startedAt:        null,
  completedAt:      null,
};

export const stateAnnotation = {
  companyName:      { value: (old, next) => next ?? old, default: () => "" },
  companyProfile:   { value: (old, next) => next ?? old, default: () => null },
  ticker:           { value: (old, next) => next ?? old, default: () => "" },
  financialData:    { value: (old, next) => next ?? old, default: () => null },
  financialScore:   { value: (old, next) => next ?? old, default: () => 0 },
  recentNews:       { value: (old, next) => next ?? old, default: () => [] },
  newsScore:        { value: (old, next) => next ?? old, default: () => 0 },
  sentimentResult:  { value: (old, next) => next ?? old, default: () => null },
  sentimentScore:   { value: (old, next) => next ?? old, default: () => 0 },
  riskFactors:      { value: (old, next) => next ?? old, default: () => [] },
  riskScore:        { value: (old, next) => next ?? old, default: () => 0 },
  moatAnalysis:     { value: (old, next) => next ?? old, default: () => "" },
  verdict:          { value: (old, next) => next ?? old, default: () => "" },
  confidenceScore:  { value: (old, next) => next ?? old, default: () => 0 },
  reasoning:        { value: (old, next) => next ?? old, default: () => "" },
  summary:          { value: (old, next) => next ?? old, default: () => "" },
  steps:            { value: (old, next) => next ?? old, default: () => [] },
  errors:           { value: (old, next) => next ?? old, default: () => [] },
  startedAt:        { value: (old, next) => next ?? old, default: () => null },
  completedAt:      { value: (old, next) => next ?? old, default: () => null },
};